name: torch_render2
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch==2.6.0
    - torchvision
    - torchaudio
    - numpy
    - scipy
    - matplotlib
    - pandas
    - jupyter
    - ipykernel
    - absl-py
    - cachetools
    - charset-normalizer
    - git+https://github.com/MPI-IS/configer
    - configparser
    - dotmap
    - freetype-py
    - future
    - google-auth
    - google-auth-oauthlib
    - grpcio
    - idna
    - imageio
    - markdown
    - networkx
    - oauthlib
    - opencv-python
    - pillow
    - protobuf
    - pyasn1
    - pyasn1-modules
    - pyglet
    - pyopengl
    - pyrender
    - pytorch-lightning>=2.0
    - pywavelets
    - pyyaml
    - requests
    - requests-oauthlib
    - rsa
    - scikit-image
    - smplx
    - tensorboard
    - tensorboardx
    - tifffile
    - torchgeometry
    - tqdm
    - transforms3d>=0.4.2
    - trimesh
    - urllib3
    - werkzeug
